name: Release Branch and Bump Version (Manual)

on:
  workflow_dispatch:  # Triggered by manual workflow dispatch
    inputs:
      issue_number:
        required: true
        type: string
      release_number:
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Bump version (replace with your actual version bumping logic)
        run: |
          # Replace with your specific command to bump version to RELEASE_NUMBER
          echo This is a placeholder, replace with your version bumping command
          bash "echo 'Bumping version to ${{ inputs.release_number }}' >> README.md"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git commit -m "${{ inputs.issue_number }}: Bump app version to ${{ inputs.release_number }}"
          git push

      - name: Create release branch
        run: |
          BRANCH_NAME=${{ inputs.issue_number }}-release-${{ inputs.release_number }}
          git checkout -b BRANCH_NAME
          git push origin -u BRANCH_NAME
