name: Release Branch and Bump Version (Manual)

env:
  GRADLE_FILE_NAME: app/build.gradle

on:
  workflow_dispatch: # Triggered by manual workflow dispatch
    inputs:
      issue_number:
        description: 'Issue number in format MOBILE-123'
        required: true
        type: string
      release_number:
        description: 'Release number in format 1.0.0'
        required: true
        type: string
      version_code:
        description: 'Version code in format 567 (optional)'
        required: false
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check inputs
        run: |
          issue_number=${{ inputs.issue_number }}
          if [[ ! $issue_number =~ ^MOBILE-[0-9]{5,} ]]; then
            echo "Error: Invalid issue number format. Must start with 'MOBILE-' and have at least 5 digits."
            exit 1
          fi
          
          release_number=${{ inputs.release_number }}
          if [[ ! $release_number =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Invalid release number format. Must be in the format 'X.X.X'."
            exit 1
          fi
          
          version_code=${{ inputs.version_code }}
          if [[ -z "$version_code" ]]; then
            echo "version_code is not provided. Skipping validation."
          elif [[ ! $version_code =~ ^[0-9]{3,}$ ]]; then
            echo "Error: Invalid version_code format. Must be at least 3 digits."
            exit 1
          fi

      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Create release branch
        run: |
          RELEASE_BRANCH_NAME=${{ inputs.issue_number }}-release-${{ inputs.release_number }}
          git checkout -b $RELEASE_BRANCH_NAME
          git push origin -u $RELEASE_BRANCH_NAME

      - name: Bump app version
        run: |
          chmod +x scripts/increment_app_version.sh
          ./scripts/increment_app_version.sh $GRADLE_FILE_NAME ${{ inputs.release_number }} ${{ inputs.version_code }}

      - name: Commit updated app version
        run: |
          git diff
          git add app/build.gradle
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          git commit -m "${{ inputs.issue_number }}: Bump app version to ${{ inputs.release_number }}"
          git push origin $RELEASE_BRANCH_NAME

      - name: Add build tag
        run: |
          ISSUE=${{ inputs.issue_number }}
          ISSUE_NUMBER=${ISSUE#*-}
          TAG=rc_${{ inputs.release_number }}.1_${ISSUE_NUMBER}
          git tag $TAG
          git push origin $TAG

      - name: Create cherry pick branch
        run: |
          CHERRY_PICK_BRANCH=${{ inputs.issue_number }}-version-to-dev-${{ inputs.release_number }}
          LAST_COMMIT=$(git log -1 --pretty=%H)
          echo "Last commit: $LAST_COMMIT"
          git checkout -b $CHERRY_PICK_BRANCH dev
          git cherry-pick $LAST_COMMIT
          git push origin $CHERRY_PICK_BRANCH

      - name: Create pull request
        run: |
          gh pr create --base dev --fill --reviewer ${{ github.actor }}
          gh pr merge --admin --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
          
      
          
