name: Release Branch and Bump Version (Manual)

on:
  workflow_dispatch:  # Triggered by manual workflow dispatch
    inputs:
      issue_number:
        description: 'Issue number in format MOBILE-123'
        required: true
        type: string
      release_number:
        description: 'Release number in format 1.0.0'
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Bump app version
        run: |
          chmod +x scripts/increment_app_version.sh
          ./scripts/increment_app_version.sh ${{ inputs.release_number }}
          
      - name: Commit updated app version
        run: |
          git add app/build.gradle
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git commit -m "${{ inputs.issue_number }}: Bump app version to ${{ inputs.release_number }}"
          git push

      - name: Create release branch
        run: |
          BRANCH_NAME=${{ inputs.issue_number }}-release-${{ inputs.release_number }}
          git checkout -b $BRANCH_NAME
          git push origin -u $BRANCH_NAME

      - name: Add build tag
        run: |
          ISSUE=${inputs.issue_number}
          ISSUE_NUMBER=${ISSUE#*-}
          TAG=rc_${{ inputs.release_number }}.1_${{ ISSUE_NUMBER }}
          git tag $TAG
          git push origin $TAG
          
